name: Test Using Mocha

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test
      - run: echo "All test passed"